//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLUI.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLUI.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Style 的當地語系化字串。
        /// </summary>
        public static string ChangeStyle {
            get {
                return ResourceManager.GetString("ChangeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Eraser 的當地語系化字串。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move 的當地語系化字串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Begin Position 的當地語系化字串。
        /// </summary>
        public static string MoveBegin {
            get {
                return ResourceManager.GetString("MoveBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Center 的當地語系化字串。
        /// </summary>
        public static string MoveCenter {
            get {
                return ResourceManager.GetString("MoveCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move End Position 的當地語系化字串。
        /// </summary>
        public static string MoveEnd {
            get {
                return ResourceManager.GetString("MoveEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Max Position 的當地語系化字串。
        /// </summary>
        public static string MoveMax {
            get {
                return ResourceManager.GetString("MoveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Min Position 的當地語系化字串。
        /// </summary>
        public static string MoveMin {
            get {
                return ResourceManager.GetString("MoveMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Toward 的當地語系化字串。
        /// </summary>
        public static string MoveToward {
            get {
                return ResourceManager.GetString("MoveToward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pen 的當地語系化字串。
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename 的當地語系化字串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select 的當地語系化字串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Undo 的當地語系化字串。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
